### ISSUE TITLE
Data Query?

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/lrw-udd-api#3]
How to we query based on dates?

"a specific example we have is where we’re querying for records with an updatedDt >= some instant in time, thus:

{ “updatedDt” : { “$gte” : “<ISO8601 time string>” } }

**Comment by amason** [comment]
Per Andrew, he provided the following:

"Is updatedDt field a valid field for the objects that get returned from these API’s?  it’s hard to tell from the unfiltered view since the API doesn’t return that kind of meta data as it standsThe fields are UPDATED_AT and CREATED_AT. You should be getting those back unless it's filtered by the scope on your particular API credentials. I'll look into it.

does the query syntax support additional clauses, e.g. if i wanted to query a *range* of updatedDt’s, the logical equiv of ($gte low AND $lt high)
Yep https://jiscv2.learninglocker.net/api/jisc/v1.2.1/student?populate="studentAdditional"&query={"UPDATED_AT":{"$gte":"2016-05-01T00:00:00.000Z","$lt":"2016-05-10T00:00:00.000Z"}} <https://jiscv2.learninglocker.net/jisc/v1.2.1/student?populate=%22studentAdditional%22&amp;query=%7B%22UPDATED_AT%22:%7B%22$gte%22:%222016-05-01T00:00:00.000Z%22,%22$lt%22:%222016-05-10T00:00:00.000Z%22%7D%7D>

**Comment by amason** [comment]
@michaelwebbjisc We have what we need here from Andrew's response. I think we can close this one out.
