### ISSUE TITLE
API UDD 1.2.4 - STUDENT entity - LAST_NAME & FIRST_NAME cannot be null - CHECK

### ISSUE THREAD

**Issue by robwynj** [jiscdev/lrw-udd-api#30]
Hia,

Can you check on this please - as FIRST_NAME & LAST_NAME in STUDENT should be optional. I just wanted to check with you, if this is still the case with the API validation please.

Many Thanks

Rob

**Comment by ht2** [comment]
No, looks like they are mandatory. I can see the commit where this took place: https://github.com/jiscdev/analytics-udd/commit/ba49e02cb2b0bbf449a73632986230bc83407cf4. It looks like there were a large amount of optional fields added in this release that didn't actually get applied to the release.

Short of going through field by field I'm not 100% of the best way to ensure they match. I think we'll simply have to do that (and I will begin action on that today), but there does still feel like a missing step in regards to a "version changes" document at each release that explicitly details what has changed since the last version. We can use this to make the relevant changes at the code end, and consumers of the API will be able to use it to compare backwards compatibility between releases.

**Comment by robwynj** [comment]
Looks like the v1.2.4 (current version) has them documented as [0..1] - will check with Wilbert on this too!

Kind Regards

Rob

**Comment by ht2** [comment]
Sorry, by mandatory in the codebase, I mean in the deployed API. I can see in the github release (and commit I linked to) that they are optional

**Comment by wilmTap** [comment]
In v1.2.4 of the UDD, LAST_NAME and FIRST_NAME were mandatory, but they were part of student_additional, and that whole entity was optional. Because it wasn't entirely clear what that meant – I took it to mean: if you're going to do student_additional, you have to have LAST_NAME and FIRST_NAME –, student_additional was merged with student in v1.2.5 and all its properties made optional.

I've made a list of [changes of v1.2.3 to v1.2.4](https://github.com/jiscdev/analytics-udd/pull/72), and [one for the changes from v1.2.4 to v1.2.5](https://github.com/jiscdev/analytics-udd/pull/91), which is repeated on [the v1.2.5 release notes](https://github.com/jiscdev/analytics-udd/releases/tag/v1.2.5). I'd like to make it as useful as possible for people, so if a different form or place for these diff lists would work better, please let me know.
