### ISSUE TITLE
UDD API 1.2.5 - STUDENTCOURSEMEMBERSHIP.COURSE_AIM_ATTAINED - Should be optional

### ISSUE THREAD

**Issue by robwynj** [jiscdev/lrw-udd-api#33]
Should allow NULL values through, as per UDD 1.2.5, as field is optional?

Many Thanks

Rob

**Comment by ht2** [comment]
Confirmed.

Looks like this was missed off the release notes: https://github.com/jiscdev/analytics-udd/releases/tag/v1.2.5

Highly likely there is other stuff then...

**Comment by ht2** [comment]
OK, so having a deeper look into this. Technically the field is not required in our schema, but because we have an `enum` validation of the aimCodes, `null` doesn't validate! 

If you actually leave the field off when POSTing the result it goes into the DB correctly, so for the meantime do that whilst I patch a fix.

**Comment by ht2** [comment]
I'd had a search and I don't believe there to be any other fields that match the pattern of allowing null, but being validated with an enum.

**Comment by ht2** [comment]
Morning Rob, I've patched the JISC UDD API and the stable/v1.2.5 endpoints now allow null as a valid entry to the COURSE_AIM_ATTAINED value.
