### ISSUE TITLE
UDD API 1.2.6 - MODULE.MOD_LEVEL - optional?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/lrw-udd-api#38]
Hia,

Can you confirm if this is indeed optional (as per UDD 1.2.6) on the API please?

Many Thanks

Rob

**Comment by ht2** [comment]
Hey Rob,

We've just tested this - looks like you can't pass in `null` as a value (due to the field have an `enum` restriction), but you can just not pass the field. However you then do not have a `MOD_LEVEL` key or value set in the returned model.

What's the best approach here - Is this another issue similar to https://github.com/jiscdev/analytics-udd/issues/110? It feels like adding `null` to the enum is probably our best option. Anything further to add  @andrewhickey?

**Comment by robwynj** [comment]
Hi Andrew,

Can you add a NULL to the enum here please, and apply this as a fix.

Many Thanks

Rob

**Comment by robwynj** [comment]
Hi Andrew,

Can you update me on this issue please - Many Thanks :)

Rob

**Comment by andrewhickey** [comment]
Hi Rob, this will be in the API by tomorrow evening.
